---
abstract: 'Main object representing acess to a particular Shopify store.'
author:
  - 'Adam <adamdharrison@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Shopify
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::Eksblowfish: 0
  Data::Dumper: 0
  Data::Random: 0
  String::Random: 0
version: 0.02
